### ISSUE TITLE
Error after changing folder path

### ISSUE THREAD

**Issue by XXY233** [uenz/SparkleShare#4]
### What happened:
When I add folders_path in projects.xml, the progress bar of the program will not be completed when I add hosted project, and it will crash when I add hosted project next time.  
(I just want to synchronize several files scattered in the D drive: D:\myfolder2\config.yml; D:\myfolder\test.yml. Because SparkleShare can only synchronize one folder, so I will combine them with SparkleShare The files in the folder make hard symbolic links. I don't know if there is any other better way.)
```
<sparkleshare>
  <user>
    <name>xxx</name>
    <email>xxx@gmail.com</email>
  </user>
  <folders_path>d:\SparkleShare</folders_path>
  <notifications>False</notifications>
</sparkleshare>
```

### log
```
01:10:43 Environment | SparkleShare 3.38.0
01:10:43 Environment | Git LFS 2.10.0
01:10:43 Environment | Git 2.26.1.windows.1
01:10:43 Environment | SSH OpenSSH_8.2p1
01:10:44 Environment | SSH-KeyGen found
01:10:44 Environment | SSH-KeyScan found
01:10:44 Environment | OpenSSL 1.1.1f
01:10:44 Environment | Windows (Microsoft Windows NT 6.2.9200.0)
01:10:44 Cmd | ssh | ssh-keygen.exe -t ecdsa -b 521 -P "" -C "Roselle-2022991 (SparkleShare)" -f "2023-03-21_01h10.key"
01:10:44 Auth | Created key pair: 2023-03-21_01h10.key
01:11:13 Fetcher | C:\Users\Administrator\AppData\Roaming\org.sparkleshare.SparkleShare\tmp\language-files.git | Fetching folder: ssh://git@gitee.com/toiletmc/language-files.git
01:11:13 Auth | Fetching host key for gitee.com
01:11:13 Cmd | ssh-keyscan.exe -t rsa -p 22 gitee.com
01:11:13 Auth | Skipping fingerprint check
01:11:13 Auth | Accepted host key for gitee.com
01:11:13 Cmd | tmp | git.exe ls-remote --heads "ssh://git@gitee.com/toiletmc/language-files.git"
01:11:14 Fetcher | Failed
01:11:38 Fetcher | C:\Users\Administrator\AppData\Roaming\org.sparkleshare.SparkleShare\tmp\language-files.git | Fetching folder: ssh://git@gitee.com/toiletmc/language-files.git
01:11:38 Auth | Fetching host key for gitee.com
01:11:38 Cmd | ssh-keyscan.exe -t rsa -p 22 gitee.com
01:11:38 Auth | Skipping fingerprint check
01:11:38 Cmd | tmp | git.exe ls-remote --heads "ssh://git@gitee.com/toiletmc/language-files.git"
01:11:39 Cmd | tmp | git.exe clone --progress --no-checkout --depth=1 "ssh://git@gitee.com/toiletmc/language-files.git" "C:\Users\Administrator\AppData\Roaming\org.sparkleshare.SparkleShare\tmp\language-files.git"
01:11:39 Git | Cloning into 'C:\Users\Administrator\AppData\Roaming\org.sparkleshare.SparkleShare\tmp\language-files.git'...
01:11:39 Git | remote: Enumerating objects: 6, done.        
01:11:39 Git | remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0        
01:11:41 Fetcher | Finished
01:11:41 Cmd | language-files.git | git.exe rev-parse HEAD
01:11:41 Cmd | language-files.git | git.exe config core.autocrlf true
01:11:41 Cmd | language-files.git | git.exe config core.quotepath false
01:11:41 Cmd | language-files.git | git.exe config core.precomposeunicode true
01:11:41 Cmd | language-files.git | git.exe config core.ignorecase false
01:11:41 Cmd | language-files.git | git.exe config core.filemode false
01:11:41 Cmd | language-files.git | git.exe config core.safecrlf false
01:11:41 Cmd | language-files.git | git.exe config core.excludesfile ""
01:11:41 Cmd | language-files.git | git.exe config core.packedGitLimit 128m
01:11:41 Cmd | language-files.git | git.exe config core.packedGitWindowSize 128m
01:11:41 Cmd | language-files.git | git.exe config pack.deltaCacheSize 128m
01:11:41 Cmd | language-files.git | git.exe config pack.packSizeLimit 128m
01:11:41 Cmd | language-files.git | git.exe config pack.windowMemory 128m
01:11:41 Cmd | language-files.git | git.exe config push.default matching
01:11:42 Cmd | language-files.git | git.exe config filter.lfs.required true
01:11:42 Cmd | language-files.git | git.exe config filter.lfs.clean ''C:/Program Files (x86)/SparkleShare/git_scm/mingw32/bin/git-lfs.exe' clean %f'
01:11:42 Cmd | language-files.git | git.exe config filter.lfs.smudge "env GIT_SSH_COMMAND='\"C:/Program Files (x86)/SparkleShare/git_scm/usr/bin/ssh.exe\" -i \"C:/Users/Administrator/AppData/Roaming/org.sparkleshare.SparkleShare/ssh/2023-03-21_01h10.key\" -o UserKnownHostsFile=\"C:/Users/Administrator/AppData/Roaming/org.sparkleshare.SparkleShare/ssh/known_hosts\" -o IdentitiesOnly=yes -o PasswordAuthentication=no -F /dev/null' 'C:/Program Files (x86)/SparkleShare/git_scm/mingw32/bin/git-lfs.exe' smudge %f"
01:11:42 Cmd | language-files.git | git.exe rev-parse HEAD
01:11:42 Cmd | language-files.git | git.exe show-ref --verify --quiet refs/heads/SparkleShare
01:11:42 Cmd | language-files.git | git.exe checkout --quiet --force HEAD
01:11:42 Controller | Error moving directory, trying again...: The source and target paths must have the same root. Move operation is not valid between volumes.    at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at SparkleShare.BaseController.FinishFetcher(StorageType selected_storage_type)
01:11:42 Controller | Error moving directory: at System.IO.Directory.InternalMove    at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at SparkleShare.BaseController.FinishFetcher(StorageType selected_storage_type)
01:14:44 Fetcher | Failed to delete 'C:\Users\Administrator\AppData\Roaming\org.sparkleshare.SparkleShare\tmp\language-files.git': Access to path 'pack-d549c5c0ab6904425daedd99783f823ca0efaf87.idx' is denied.    at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Sparkles.Git.GitFetcher.Stop()

```

**Comment by uenz** [comment]
Was not here for a while. Sorry
